version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_feedback
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etl/sql/init.sql:/docker-entrypoint-initdb.d/00_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d customer_feedback"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    build: .
    command: python /app/app.py
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app_network

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge

